name: dhscanner

on:
  push:
    branches:
      - '**'  # trigger on *any* branch push
  pull_request:
    branches:
      - '**'  # trigger on *any* pull request

jobs:
  run-dhscanner:
    runs-on: ubuntu-latest
    steps:
      - uses: OrenGitHub/dhscanner-action@v1.0.3
